config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'
	
	get 'carts/remove' => 'settings#remove', :as => :remove

	resources :products do
		get :who_bought, on: :member
	end

	root :to =>'store#index', :as =>'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>
<%= content_tag :body, class: controller.controller_name do %>
	<div id="banner">
		<%= image_tag("logo.png") %>
		<%= @page_title || "Pragmatic Bookshelf" %>
	</div>
  <div id="columns">
  <div id="side">
   <ul>
	<li><%= link_to 'Item Listing', store_path %></li>
	<li><%= link_to 'News', store_path %></li>
	<li><%= link_to 'About', store_path %></li>
	<li><%= link_to 'Contact', store_path %></li>
	</ul>
	<span id='DateTime' class="nowrap">The time is:
		<%= Time.now.strftime("%H:%M") %>
	</span>
	<span id='DateTime' class="nowrap">The date is: 
		<%= Time.now.strftime("%d/%m/%Y") %>
	</span>
	<% if @cart %>
	  <div id="cart">
	    <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
 			<%= render @cart %>
			<% end %>
	  </div>
	<% end %>
		<% if session[:user_id] %>
			<br />
			<%= link_to 'Orders',   orders_path   %><br />
			<%= link_to 'Products', products_path %><br />
			<%= link_to 'Users',    users_path    %><br />
			<br />
			<%= button_to 'Logout', logout_path, :method => :delete   %>
		<% end %>

  </div>
  <div id="main">
    <%= yield %>
  </div>
</div>
<% end %>
</body>
</html>